services:
  postgres:
    image: "postgres:16.3-alpine"
    container_name: IccDatabase
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-knudevpass}
      POSTGRES_DB: icc_db
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - icc-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2024-10-13T13-34-11Z
    container_name: minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY:-minioadmin}
    command: server /data --console-address :9090
    ports:
      - "9000:9000" # MinIO API
      - "9090:9090" # MinIO Console
    volumes:
      - minio-data:/data
    networks:
      - icc-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: olympicgay/icc-app-backend:latest
    platform: linux/amd64
    container_name: icc-app
    restart: unless-stopped
    environment:
      # Database Configuration
      SPRING_DATASOURCE_URL: ${DB_URI:-jdbc:postgresql://postgres:5432/icc_db}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-knudevpass}

      MINIO_INTERNAL_URL: http://minio:9000
      MINIO_EXTERNAL_URL: http://localhost:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-minioadmin}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-minioadmin}
      MINIO_USE_PROXY: "true"

      # Application Configuration
      BASE_URL: http://localhost:5003
      SPRING_PROFILES_ACTIVE: dev
      APPLICATION_PORT: 5003

    ports:
      - "5003:5003"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - icc-network


volumes:
  db-data:
    driver: local
  minio-data:
    driver: local

networks:
  icc-network:
    driver: bridge
