services:
  # === PostgreSQL Database ===
  - type: web
    name: icc-database
    plan: free
    env: docker
    image:
      url: docker.io/library/postgres:16.3-alpine
    envVars:
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        value: knudevpass
      - key: POSTGRES_DB
        value: icc_db

  # === MinIO Object Storage ===
  - type: web
    name: minio
    plan: free
    env: docker
    image:
      url: "docker.io/minio/minio:RELEASE.2024-10-13T13-34-11Z"
    envVars:
      - key: MINIO_ROOT_USER
        value: minioadmin
      - key: MINIO_ROOT_PASSWORD
        value: minioadmin

  # === Spring Boot Backend ===
  - type: web
    name: icc-app-backend
    plan: free
    env: docker
    image:
      url: "olympicgay/icc-app-backend:latest"
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://icc-database:5432/icc_db
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres
      - key: SPRING_DATASOURCE_PASSWORD
        value: knudevpass

      - key: MINIO_INTERNAL_URL
        value: http://minio:9000
      - key: MINIO_EXTERNAL_URL
        value: https://minio.onrender.com
      - key: MINIO_ACCESS_KEY
        value: minioadmin
      - key: MINIO_SECRET_KEY
        value: minioadmin
      - key: MINIO_USE_PROXY
        value: "true"

      - key: JWT_SECRET_KEY
        value: OblBr1u8BlwbqA61vt0yk4TC/mPlvT2O+t2m9SCci6g=
      - key: BASE_URL
        value: https://icc-app-backend.onrender.com
      - key: SPRING_PROFILES_ACTIVE
        value: dev
      - key: APPLICATION_PORT
        value: "5003"
