spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/icc_db
    username: postgres
    password: 12082007
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true

server:
  port: 5001

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
